### ISSUE TITLE
Path parameter for all subscriptions

### ISSUE THREAD

**Issue by ac360** [serverless/event-gateway#149]
Could you provide some clarity on how Subscription Paths work?

- Are Paths available for all events or only `http` events?
- If Paths are available for all events, are they optional?

Having Paths only work for `http` events is not my preference because it creates a confusing happenstance.  At the same time, Paths are just like Channels (a longstanding concept in event-driven architectures) and are useful for all events.

My preference would be to have Paths work for all Events, but having them be optionally included in the Subscription is interesting, since it reduces the requirement that people hardcode Paths into their logic, makes config simpler, and ultimately makes getting started easier.  As an application/architecture grows, allowing Paths to be optionally embraced later will help keep things organized, segregated and more governable.

**Comment by mthenw** [comment]
Right now `path` parameter is required only for `http` subscription type. Any other subscriptions (custom event) doesn't require this parameter. 

I'm marking this as a feature request.

**Comment by mthenw** [comment]
Already done https://github.com/serverless/event-gateway/commit/311b2bfa0e8dba34a117ef6b0614de49cfc5e14f
