### ISSUE TITLE
How Do Direct Function Calls Work?  Are They Event-Driven?

### ISSUE THREAD

**Issue by ac360** [serverless/event-gateway#155]
https://github.com/serverless/event-gateway#example-function-to-function-call

How does the Event Gateway treat this?  Also, on the surface, this feature appears to side-step the singular event-driven experience of the Event Gateway.  Is this feature event-driven?  If not, how can it be?

**Comment by mthenw** [comment]
I had a hard time figuring out how to implement invocation (should it be part of config api or event api). I think that Brian's proposition is nice, I like it. I need to figure out how to implement that.

**Comment by mthenw** [comment]
@brianneisler do you have any idea how to pass function name in that case?

**Comment by mthenw** [comment]
Closing this one as sync invocation has been implemented as a special event type: https://github.com/serverless/event-gateway#invoking-a-registered-function-sync-function-invocation.
