### ISSUE TITLE
AWS Lambda Invocation Security Creds

### ISSUE THREAD

**Issue by shortjared** [serverless/event-gateway#186]
I see that https://github.com/serverless/event-gateway/issues/15 was closed.

You should be able to support all of the valid AWS permissions with fairly low overhead. The SDKs are setup to look at hard coded, environment variables, shared creds file, then metadata service. (The security preference is the reverse order). http://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html

I would expect the gateway to at a minimum support the ec2 role based auth. Particularly I would want to be able to trust the event-gateway role / account to invoke my lambda functions without having to provide hard coded credentials when registering the functions. No need to worry about key rotations, exposure, etc.

https://read.iopipe.com/public-cross-account-functions-on-aws-lambda-bcc148303083

**Comment by shortjared** [comment]
I submitted a PR that gives an idea for how to solve this. It should be minimal changes, loses no functionality,  huge security win.

**Comment by mthenw** [comment]
Hey @shortjared, you are absolutely right. Thanks for that PR!
