### ISSUE TITLE
Route events to external system (Kafka, Kinesis)

### ISSUE THREAD

**Issue by shortjared** [serverless/event-gateway#189]
I was working on adding Amazon Kinesis as a provider.

However, I realized that having knowledge of the topicID is pretty critical because I need it for making sure events from different topics pass through the same shards via the PartitionKey.

Any way to get access to the `TopicID` for usage in the function call methods would be awesome.

```go
func (f *Function) callAmazonKinesis(topicID string, payload []byte) ([]byte, error) {
	amazonkinesis := kinesis.New(session.New(aws.NewConfig().WithRegion(f.Provider.Region)))

	if f.Provider.AWSAccessKeyID != "" {
		creds := credentials.NewStaticCredentials(f.Provider.AWSAccessKeyID, f.Provider.AWSSecretAccessKey, "")
		amazonkinesis = kinesis.New(session.New(aws.NewConfig().WithRegion(f.Provider.Region).WithCredentials(creds)))
	}

	partitionkey := "unimplemented"
	putRecordOutput, err := amazonkinesis.PutRecord(&kinesis.PutRecordInput{
		StreamName:   &f.Provider.StreamName,
		Data:         payload,
		PartitionKey: &partitionkey,
	})

	return []byte(*putRecordOutput.SequenceNumber), err
}

```

**Comment by mthenw** [comment]
Interesting idea with adding Kinesis as a function provider. How would like to achieve sync subscriptions with that?

**Comment by shortjared** [comment]
I don't actually think we need sync for Kinesis and the point wasn't really kinesis or anything about the subscriber specifically. It's more that the topicID being targeted should be passed down.

Perhaps we need a way to mark a subscriber as async only as well?

**Comment by mthenw** [comment]
I think that we need another concept here. Registering Kinesis stream as a function feels weird. I think it could be solved either by connectors or some kind of middleware that would export events to some external system.

**Comment by shortjared** [comment]
Totally agreed.

Essentially I want the event gateway to actually serve as the broker for stream shuttling. Whether it be Kafka, Firehouse, Kinesis, etc. Seems like a pretty key use case for the gateway. Exec'ing functions is great, but I'd imagine just being able to fork a stream is just as valuable. I would want to be able to subscribe these "shuttle targets" against 1 or more topics, potentially with the filtering and such also coming.

**Comment by mthenw** [comment]
Yeah, right now the only solution is to use a function that will pipe events. I'm marking this as a feature request.

**Comment by alexdebrie** [comment]
I'd plus-one this as a feature. I've done some work previously that had a Lambda function dumping directly into a Kinesis stream or Firehose. It'd be great to skip the need for that Lambda function entirely. It'd also be a way to bootstrap persistence in for users that need it.

This could also be really helpful to get around the Kinesis read requests limits. You could hook up multiple Kinesis streams to a single event, so the Marketing team could have their stream with 3-4 use cases, and different product teams could add their own streams as well.

**Comment by mthenw** [comment]
We recently added few connectors (AWS Kinesis, AWS Firehose, AWS SQS)
https://github.com/serverless/event-gateway/pull/399
https://github.com/serverless/event-gateway/pull/394
https://github.com/serverless/event-gateway/pull/392

Closing this one.
