### ISSUE TITLE
Params and wildcards in paths in HTTP subscription

### ISSUE THREAD

**Issue by brianneisler** [serverless/event-gateway#217]

**Comment by mthenw** [comment]
There should be an ability to define subscription `path` field with params and wildcards. Params and wildcards are highly inspired by https://github.com/julienschmidt/httprouter#named-parameters.

# Parameter

Path `/users/:id` means that there is a parameter called "id". The value of this parameter is passed in HTTP event `data` field

```
{
  ...
  "data": {
    "headers": <request headers>,
    "query": <request query params>,
    "body": <request payload>,
    "path": <request URL path>,
    "method": <request method>,
    "params": {
      "id": "..."
    }
  }
  ...
}
```
EG should prevent from registering conflicting paths so e.g. there should no way to create subscriptions with `/users/new` and `/user/:id` paths.

# Wildcard

`/*filename`

Wildcard is a special type of parameter that matches everything. So it can be defined only at the end of the path. Similarly to param, wildcard value is passed to the function in HTTP event object in `params` field.
