### ISSUE TITLE
Add link to FDK and Framework from event-gateway readme

### ISSUE THREAD

**Issue by brianneisler** [serverless/event-gateway#223]
This project shows many examples using the framework and FDK but does not explain that it is related to those projects. We should call out those examples and link to the projects from here.

**Comment by mthenw** [comment]
I created separate repo for that https://github.com/serverless/event-gateway-examples

**Comment by mthenw** [comment]
I will add link to the framework once `sls run` is released. https://github.com/serverless/event-gateway/issues/237
