### ISSUE TITLE
Status call on Config API can validate presence of provider creds

### ISSUE THREAD

**Issue by rupakg** [serverless/event-gateway#240]
Since we have a status call `/v1/status` on the Config API, I would think that it would be really useful to add functionality, to check if the system can access the provider creds. The creds do not have to be displayed but a simple message like:

- "AWS creds are set." - Azure/GCF/OpenWhisk can be identified as well.
- "Provider creds are not set." - if nothing is found

**Comment by mthenw** [comment]
@rupakg, each function can have different creds. Checking it for every function might be problematic if there is a lot of functions. Also, right now, only AWS support dry-run invoke for checking creds. It's not supported by other providers. 

I'm gonna close this issue as there is already one about validating creds https://github.com/serverless/event-gateway/issues/168.
