### ISSUE TITLE
HTTP subscription response schema 

### ISSUE THREAD

**Issue by mthenw** [serverless/event-gateway#245]
To respond to an HTTP event a function needs to return object with following fields:		
- `statusCode` - `int` - response status code, default: 200		
- `headers` - `object` - response headers		
- `body` - `string` - response body

**Comment by mthenw** [comment]
I had to revert that change. I thought that we can do that without conflicting with async functions but we cannot.

Basically, if the subscription is `http` we MUST require special response object, it cannot be optional. Trying to figure out if user returned HTTP response object or just some random object is impossible and creates confussion. BTW, this is how API Gateway works right now.

So once HTTP subscription is created backing function need to implement that structure, if not error from EG should be returned.

**Comment by brianneisler** [comment]
Makes sense to me that we would require the response structure for http subscriptions.
