### ISSUE TITLE
How does load balancing work for the event-gateway?

### ISSUE THREAD

**Issue by brianneisler** [serverless/event-gateway#248]

**Comment by mthenw** [comment]
@brianneisler what kind of load balancing do you mean?

**Comment by brianneisler** [comment]
Hey @mthenw, sorry should have been more clear. The docs don't clearly call out how the event-gateway is meant to be load balanced. From our earlier discussions, the thought was that the event-gateway was meant to live at the edge meaning it IS the balancer. 

First, I wanted to check if that was still the plan. If so, we should document that somewhere in the readme. Second, what would be the suggested DNS balancing strategy? How does the gateway operate if it has nodes running in every provider? Does an event get forwarded to the node running on that provider before making the call to invoke the function? Any other clarity around what the strategy will look like here would be good to know. 

A side note, I'm also wondering what it would look like to support persistent client connections like websockets and how that would operate.

**Comment by mthenw** [comment]
EG can be either at the edge or it can run behind LB (AWS ELB, etc) depending on the use case, traffic, perf requirements nd other factors. It must be capable of being edge proxy/LB which means it has to have enough security features (TLS, timeouts).

> What would be the suggested DNS balancing strategy?
Depending on the use case. By default, I would always propose to run it behind LB. That's the easiest way. In other cases DNS round robin might be the case.

> How does the gateway operate if it has nodes running in every provider?
Backing etcd needs to run somewhere, in one region. All EG instances connect to that etcd. EG is a stateless service.

> Does an event get forwarded to the node running on that provider before making the call to invoke the function?

No need for that as all instances use the same state (stored in etcd). Routing this event would only add latency.

> A side note, I'm also wondering what it would look like to support persistent client connections like websockets and how that would operate.

That's something to figure out. I don't have any solution for that right now. EG is a stateless, eventually consistent service. Supporting persistent connections means that we would have to add partitioning for users' sessions. That's a bit different problem to solve.

**Comment by rupakg** [comment]
@mthenw So can I run three instances of EG today, and they form a cluster and sync on etcd? If that is the case, then should I be able to just hit any EG instance url (Event/Config API) and it will just work? 

Just curious. Is that a future plan?

**Comment by mthenw** [comment]
@rupakg it's possible right now. You just need to provide etcd address with `-db-hosts` flag.

**Comment by brianneisler** [comment]
@mthenw thanks for the replies. I've added a couple of issues around documenting some of your responses. #262 #263
