### ISSUE TITLE
Use 404 instead of 500 when no subscriptions are found for an HTTP event

### ISSUE THREAD

**Issue by ac360** [serverless/event-gateway#265]
The 404 HTTP status code should be used in this case, instead of 500.  This is common behavior for APIs and API Gateways.

I also suggest not making the error message mention functions.  Instead, go with something common, like "route not found" or "missing route".

**Comment by mthenw** [comment]
Good point! Fixing it right now.

**Comment by ac360** [comment]
The current error message is `unable to look up backing function`.  

We'd like to present this as a real alternative to existing API Gateways.  Therefore, I don't think the concept of "function" should be presented to API consumers.  This info isn't relevant to them and they shouldn't be aware of it.  Instead, I recommend something more general, like:

`Resource not found`
