### ISSUE TITLE
Allow lowercase HTTP method and path w/o slash

### ISSUE THREAD

**Issue by mthenw** [serverless/event-gateway#272]

**Comment by dschep** [comment]
It should be noted that the current requirement for a leading slash (`/`) causes errors with the [HTTP event in the serverless templates](https://github.com/serverless/serverless/blob/c7cb2db1a1d1b95f32dbd1bde65ce956274a531c/lib/plugins/create/templates/aws-nodejs/serverless.yml#L66).
