### ISSUE TITLE
Lambda function is not invoked asynchronously on an async subscription

### ISSUE THREAD

**Issue by brianneisler** [serverless/event-gateway#282]
We should be using the `Event` InvocationType when invoking a lambda function for an async subscription. Currently it appears everything is invoked using `RequestResponse`. 

http://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html#API_Invoke_RequestSyntax

**Comment by mthenw** [comment]
FYI, it's not a bug, it's by design. 

Switching to `Event` Invocation Type means that we lose control and feedback about function invocation. We will lose information about function result, if the call was successful, we will lose the ability to get logs (AWS Lambda).
