### ISSUE TITLE
Running in Docker (error in dep ensure)

### ISSUE THREAD

**Issue by barfet** [serverless/event-gateway#314]
When I tried to run event-gateway locally in Docker with `docker build -t event-gateway .` got the next error
```
grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree
The command '/bin/sh -c dep ensure' returned a non-zero code: 1
```

Docker for Windows on Windows 10 x64
Anyone faced similar issue?

Thanks.

**Comment by rupakg** [comment]
@barfet I will give it a shot and let you know. Honestly we did not test it on Windows. Your feedback to get this straightened out is very valuable. Thanks.

**Comment by barfet** [comment]
@mthenw yes, it's working now. Thanks!
