### ISSUE TITLE
Handling of Concurrent Execution Limit of AWS Lambda

### ISSUE THREAD

**Issue by barfet** [serverless/event-gateway#315]
Thanks for your efforts!

I have a question regarding the subj. ([one](http://docs.aws.amazon.com/lambda/latest/dg/concurrent-executions.html), [two](https://read.acloud.guru/does-aws-lambda-keep-its-serverless-marketing-promise-of-continuous-scaling-e990114bb379))
Your framework is perfectly fit for event base communication between microservices (SNS).
But, as I can see, it won't solve the problem of Lambda throttling when Concurrent Execution Limit reached.
Is there any plans to add the (SQS, Kinesis, DynamoDB Streams etc...) to handle this problem out of the box? Or maybe some advised architectural solution for this issue?

Thanks a lot!

**Comment by mthenw** [comment]
@barfet, great question!

The solutions that SNS uses it retry mechanism. If the invocation of function failed, it will retry with exponential backoff. We definitely need to have that mechanism built-in so in this case, we don't need to use external services.

If it's an issue for you, the solution that I would recommend is to increase that limit via Support Center.

**Comment by barfet** [comment]
Great, Thanks!
It would be great to have such functionality out of the box.
