### ISSUE TITLE
TF/CloudFormation template for deploying EG (with standalone etcd cluster)

### ISSUE THREAD

**Issue by mthenw** [serverless/event-gateway#316]
Would be great to have TF or CF template/config for showing how to deploy example setup of EG with a standalone etcd cluster.

**Comment by baniol** [comment]
Should the scripts provide a basic demo setup with one EG instance or a clustered solution, with an LB, ASG and such?

**Comment by mthenw** [comment]
@baniol good question. I've been thinking about following setup:

- EG service deployed on Fargate
- 2 ALBs, one for config API another for events API. 
- etcd deployed on EC2

Ideally would be to use some existing module for etcd as this is the most complicated part. 

What do you think?

**Comment by baniol** [comment]
Looks good, with the assumption the setup will be available in 3 US regions and Ireland (Fargate availability). 
As for ALB, it allows path and host based routing, so theoretically we could use just 1.
I can take care of preparing Terraform resources.

**Comment by mthenw** [comment]
@baniol awesome!

**Comment by mthenw** [comment]
@baniol I think that for now running single region is totally fine :) Let's start with something simple.
