### ISSUE TITLE
[Metrics] Measure all the things!

### ISSUE THREAD

**Issue by spacejam** [serverless/event-gateway#32]
Now that we have prometheus wired up, let's expand the things we're measuring:

- [ ] counters for all errors (although maybe Fatal's are less useful because Prometheus is pull-based and will probably not retrieve it in time)
- [ ] latency histogram for Get's to the config database
- [ ] latency histogram for Put's to the config database

**Comment by mthenw** [comment]
Prometheus metrics were refactored recently:
https://github.com/serverless/event-gateway/pull/379
https://github.com/serverless/event-gateway/pull/384

I'm closing this for now.
