### ISSUE TITLE
Access to full or contextual request URL on http event.

### ISSUE THREAD

**Issue by plfx** [serverless/event-gateway#327]
## This is a Feature Proposal

In handling an incoming HTTP event, I need my handler to effectively make requests to "relative" urls, which it must do by constructing a new request URL relative to the incoming request URL. The current HTTP event only reports the subscription `path` that was answered, and does not include either the hostname, full request URL, or the gateway URL.

1. A handler is mapped to `/login`
2. The handler needs to make a request to `/users`
3. The handler receives an event in response to a request to `http://my-gateway.example/xyz/login`
4. The event should have fields for both the `path: "/login"` and the `gatewayUrl: "http://my-gateway.example/xyz/"`
5. The handler uses the gateway url and adds `/users` to make a request to `http://my-gateway.example/xyz/users`

**Comment by mthenw** [comment]
@plfx I've added `host` field in HTTP event. Let me know if this doesn't solve your issue.
