### ISSUE TITLE
Not possible to unsubscribe http events

### ISSUE THREAD

**Issue by pmuens** [serverless/event-gateway#333]
## This is a bug report

It looks like it's not possible to unsubscribe `http` events which ids contain "special characters".

Here's an example how this behavior can be shown / reproduced:

```
root@794cb54977e7:/app/examples/hello-world# curl http://localhost:4001/v1/subscriptions
{"subscriptions":[{"subscriptionId":"http-GET-%2Fhello","event":"http","functionId":"multi-region-helloWorld-sayhiiiiiii","method":"GET","path":"/hello"}]}
root@794cb54977e7:/app/examples/hello-world# curl -X DELETE http://localhost:4001/v1/subscriptions/http-GET-%2Fhello
404 page not found
root@794cb54977e7:/app/examples/hello-world# curl http://localhost:4001/v1/subscriptions
{"subscriptions":[{"subscriptionId":"http-GET-%2Fhello","event":"http","functionId":"multi-region-helloWorld-sayhiiiiiii","method":"GET","path":"/hello"}]}
```

I opened up another issue in the FDK repo (https://github.com/serverless/fdk/issues/71), but using `curl` shows that this seems to be an EGE issue.

**Comment by pmuens** [comment]
Digging deeper into this it looks like the key for the DB lookup (in our case the `subscriptionId`) is normalized before it's passed to the store --> https://github.com/serverless/libkv/blob/master/store/etcd/v2/etcd.go#L135-L139 and https://github.com/serverless/libkv/blob/master/store/helpers.go#L19-L21

That could be the reason that the subscription could not be found in the DB and a 404 is returned.

**Comment by mthenw** [comment]
@pmuens this issue is fixed in the master. BTW EG no longer uses etcd v2. I switched to v3.

**Comment by pmuens** [comment]
Thanks for the clarification @mthenw 👍

BTW I used `Event Gateway version: 0.5.15`
