### ISSUE TITLE
Ability to add/ generate API Keys for config/ events

### ISSUE THREAD

**Issue by paulxuca** [serverless/event-gateway#411]
## This is a Feature Proposal

Hi there!

I am currently using event-gateway in production (albeit in a non public facing manner, more so just to better coordinate AWS Lambda invocations/ events) and was wondering if there were any plans to generate API keys/ set api keys to prevent unauthorized access to the config/ gateway endpoints? A similar to experience to AWS's API Gateway Api keys (setting keys in serverless.yml, consuming via x-api-key) would be super.

Thanks for reading!

**Comment by alexdebrie** [comment]
Hey @paulxuca ! Great suggestions. I'll fill you in our current plans.

For the Events API, we're working on adding the ability to specify authorization logic on an emitted event or an HTTP endpoint. We're hoping to start on that work in the next two weeks. I'd hope to have it finished by mid to late May.

For the Config API, we haven't prioritized auth on that end as much for two reasons. First, the Config API is on a different port than the Events API, so it can be kept in a private network or have some sort of proxy in front of it that handles authorization. Second, it has a different auth model than the Events API. The Events API authorization on a particular endpoint or event will be tied to the logic of that endpoint or event itself, whereas Config API authorization is more uniform and about who can alter the Event Gateway as a whole. The former needs to be more programmable on a more granular basis, while the latter can be handled with the rough auth proxy generally.

What do you think, @paulxuca ?

cc @mthenw and @ganeshvlrk.

**Comment by alexdebrie** [comment]
Yep, we'll allow for custom authorization logic via a Lambda function to authorize or reject an event. We'll likely also have an API key based option as well, where you can specify a particular API key to be included in the `Authorization` header to authorize a request.

**Comment by paulxuca** [comment]
Cool! Thanks for the follow up. :)
