### ISSUE TITLE
Return subscription information after creating a subscription

### ISSUE THREAD

**Issue by ac360** [serverless/event-gateway#428]
The Event Gateway formats subscription IDs differently, depending on events.  E.g. the subscriptions on `http` events have totally different formatted IDs.  Other events don't.

When building tooling for the EG, this "happenstance" is frustrating to write conditional logic for.  This could be mitigated by returning the subscriptionID when you create a subscription, which can be copied and saved to a state system.

The best approach would be to do that and format subscription IDs the same way, since happenstances are the enemy of good architectures ;)

Note: I'm using the EG SDK 0.6, which might not be passing subscription IDs through.

**Comment by mthenw** [comment]
Thanks for reporting. 

It looks like SDK issue. EG Config API always returns the model.

I'm refactoring subscription model right now and the ID format will be same for all subscriptions. Nevertheless user should not create it manually. User should only rely on ID returned from the EG.

**Comment by mthenw** [comment]
@ac360 hmm, it looks like working. 

I'm using following code:
```
eventGateway
  .subscribe({
    event: 'user.created',
    functionId: 'echo'
  })
  .then(resp => console.log(resp))
```

And that's the output

```
{ space: 'default',
  subscriptionId: 'user.created,echo,%2F',
  event: 'user.created',
  functionId: 'echo',
  path: '/' }
```

I'm closing for now if it's not working for you.

**Comment by ac360** [comment]
You're right.  Thanks for checking into this. 👍
