### ISSUE TITLE
Guide for running on K8s

### ISSUE THREAD

**Issue by alexdebrie** [serverless/event-gateway#448]
Event Gateway is attractive to Kubernetes users (example: [Kelsey Hightower's KubeCon demo](https://github.com/kelseyhightower/event-gateway-on-kubernetes)).

This ticket is to add documentation and supporting scripts to make it easy to get started with Event Gateway on K8s.

**Comment by fargozhu** [comment]
I am trying to build up some k8s deployment scripts but can't move forward from the basic version due to pod insufficient cpu. Any thoughts about it?

**Comment by alexdebrie** [comment]
Hey @fargozhu, do you have an etcd cluster running?

**Comment by fargozhu** [comment]
Hi @alexdebrie , I do not...
