### ISSUE TITLE
Strange status code behavior

### ISSUE THREAD

**Issue by ac360** [serverless/event-gateway#471]
## This is a Bug Report

The EG appears to return a `202` status code when the subscription is set to `async` and a `200` status code when the subscription is set to `sync`.  This current breaks the SDK.

However, when you create both an `async` and `sync` subscription on the same path+method within the Event Gateway, the `async` subscription appears to return a `200` status code instead of a `202`.  Only briefly noticed this, so having another person verify will be useful.  If confirmed, this  currently breaks the SDK.

### Similar or dependent issues:
* https://github.com/serverless/event-gateway-sdk/issues/49

**Comment by mthenw** [comment]
That's correct, if there are only async subscription EG will return 202 Accepted. If there is a sync subscription created on the same method and path it takes control of the returned response so it can be anything actually. 

I'm closing this one as it's more an issue about SDK.
