### ISSUE TITLE
Authorization PrincipleId not being persisted

### ISSUE THREAD

**Issue by ac360** [serverless/event-gateway#479]
When using a custom authorizer with the Event Gateway, you are able to add a `principleId` to the `authorization` object, like this:

```javascript
return awsLambdaCallback(null, {
  authorization: {
    principleId: '123',
    context: {
      foo: 'bar'
    }
  }
})
```

I can verify that my code is setting `principleId`, but I do not see it show up in the next Function.  However, `context` properties do persist and show up.

**Comment by mthenw** [comment]
Hey @ac360, 

I think you have a typo in your code. It should be `principalId` not `principleId`. Just checked the docs and it's correct there https://github.com/serverless/event-gateway/blob/master/docs/event-types.md.

**Comment by ac360** [comment]
Thanks.  Was working a lot of hours yesterday :P
