### ISSUE TITLE
Defined Event Subscription not triggering function invocation 

### ISSUE THREAD

**Issue by chrisccoy** [serverless/event-gateway#519]
## This is a Bug Report
I tried slack, but invitation link appears to be expired

* What went wrong?
Subscription for custom event did not trigger function invocation. 

* What did you expect should have happened?
Custom event "emergency.patient" would be received by event-gateway and match subscription to awslambda function. based from docs [here](https://github.com/serverless/event-gateway#example-subscribe-to-an-event)
and [here](https://github.com/serverless/event-gateway#example-emit-an-event)
Perhaps I am misreading the intent of the docs, but it suggest to me that a POST to the default path should result in event "emergency.patient" to be triggered within the EG.

**Post as follows:**
```
curl --request POST \
  --url http://localhost:4000/ \
  --header 'content-type: application/json' \
  --data '{
    "eventType": "emergency.patient",
    "eventID": "66dfc31d-6844-42fd-b1a7-a489a49f65f3",
    "cloudEventsVersion": "0.1",
    "source": "/acme/paramed/patient",
    "eventTime": "1990-12-31T23:59:60Z",
    "data": { "userID": "123" },
    "contentType": "application/json"
  }'
```
**KV Store as follows:**

Events
```
{
  "eventTypes": [
    {
      "space": "default",
      "name": "http.request"
    },
    {
      "space": "default",
      "name": "emergency.patient"
    }
  ]
}
```
Functions
```
{
  "functions": [
    {
      "space": "default",
      "functionId": "findBeds",
      "type": "awslambda",
      "provider": {
        "arn": "arn:aws:lambda:us-east-1:246472886373:function:hospitalBed",
        "region": "us-east-1",
        "awsAccessKeyId": "redacted"
        "awsSecretAccessKey": "redacted"
      }
    }
  ]
}
```
Subscription
```
{
  "subscriptions": [

    {
      "space": "default",
      "subscriptionId": "YXN5bmMsZW1lcmdlbmN5LnBhdGllbnQsZmluZEJlZHMsJTJGLFBPU1Q",
      "type": "async",
      "eventType": "emergency.patient",
      "functionId": "findBeds",
      "path": "/",
      "method": "POST"
    },
    {
      "space": "default",
      "subscriptionId": "YXN5bmMsZW1lcmdlbmN5LnBhdGllbnQsZmluZEJlZHMsJTJGbWVkaWNhbCxQT1NU",
      "type": "async",
      "eventType": "http.request",
      "functionId": "findBeds",
      "path": "/",
      "method": "POST"
    }
  ]
}
```
* What was the version you used?
I am running this natively:
`go run cmd/event-gateway/main.go -dev`

```
Event received.	{"path": "/", "event": {"eventType": "http.request", 
```
I am able to act upon the above event, using the "http.request" event subscription, but ideally I am hoping to have the ability to act upon a more granular level of event, which clearly is possible, but I must be missing something pretty obvious.

**Comment by pablojudd** [comment]
Try:  --header 'content-type: application/cloudevents+json'
This worked for me. It's not documented anywhere and I had to get it out of the code for https://github.com/serverless/event-gateway-sdk

**Comment by chrisccoy** [comment]
@pablojudd thanks man, that was what I needed! Closing ...
